export const MILLISECONDS_IN_SECOND = 1000
export const MILLISECONDS_IN_MINUTE = MILLISECONDS_IN_SECOND * 60
export const MILLISECONDS_IN_HOUR = MILLISECONDS_IN_MINUTE * 60
export const MILLISECONDS_IN_DAY = MILLISECONDS_IN_HOUR * 24
export const MILLISECONDS_IN_WEEK = MILLISECONDS_IN_DAY * 7
